# Import all models here so SQLAlchemy's Base.metadata is fully populated
# before Alembic autogenerate or engine.create_all() is called.

from app.domains.users.models import User
from app.domains.auth.models import Token, TokenType
from app.domains.accounts.models import (
    AccountSnapshot,
    JournalBootstrapDispatch,
    Trade,
    TradeDirection,
    TradeSession,
    TradingAccount,
    TradingAccountProvisioningStatus,
    TradingAccountStatus,
    TradingAccountType,
    TradingPlatform,
)
from app.domains.accounts.mt5_server_catalog import Mt5ServerCatalog
from app.domains.journal.models import (
    DailyJournal,
    JournalAttachment,
    JournalMessage,
    JournalMessageType,
    JournalTemplate,
    JournalTemplateType,
    TradeJournal,
    TagGroup,
    Tag,
    TradeTag,
    Setup,
)
from app.domains.ai.models import (
    AiAgent,
    AiChatMessage,
    AiChatSession,
    AiInsight,
    AiMessageRole,
    AiUsage,
    AiUserMemory,
)
from app.domains.notifications.models import Notification, NotificationType
from app.domains.admin.models import AdminAuditEvent, ProductEvent
from app.domains.billing.models import BillingSubscription, BillingWebhookEvent
from app.domains.copy_trading.models import (
    CopyAccountPolicy,
    CopyActivityEvent,
    CopyActivityLevel,
    CopyExecutionMetric,
    CopySignalReview,
    CopyRoute,
    CopyRouteState,
    CopyTradingUserSettings,
    LotDistribution,
    MinimumFields,
    TakeProfitMode,
    TelegramConnection,
    TelegramConnectionState,
    TelegramSource,
    TelegramSourceState,
    TelegramSourceType,
    AutomationConfidence,
    ChannelMessageSample,
    ChannelProfile,
    CopiedTrade,
    ParsedAction,
    SignalThread,
    SignalThreadState,
    SymbolMapping,
    TradeIntent,
    TradeIntentState,
)

__all__ = [
    "User",
    "Token",
    "TokenType",
    "TradingAccount",
    "JournalBootstrapDispatch",
    "TradingAccountProvisioningStatus",
    "TradingAccountStatus",
    "TradingAccountType",
    "TradingPlatform",
    "Trade",
    "TradeDirection",
    "TradeSession",
    "AccountSnapshot",
    "Mt5ServerCatalog",
    "DailyJournal",
    "TradeJournal",
    "JournalMessage",
    "JournalMessageType",
    "JournalAttachment",
    "JournalTemplate",
    "JournalTemplateType",
    "TagGroup",
    "Tag",
    "TradeTag",
    "Setup",
    "AiAgent",
    "AiChatMessage",
    "AiChatSession",
    "AiInsight",
    "AiMessageRole",
    "AiUsage",
    "AiUserMemory",
    "Notification",
    "NotificationType",
    "AdminAuditEvent",
    "ProductEvent",
    "BillingSubscription",
    "BillingWebhookEvent",
    "CopyTradingUserSettings",
    "TelegramConnection",
    "TelegramConnectionState",
    "TelegramSource",
    "TelegramSourceType",
    "TelegramSourceState",
    "CopyAccountPolicy",
    "CopyRoute",
    "CopyRouteState",
    "TakeProfitMode",
    "LotDistribution",
    "MinimumFields",
    "CopyActivityEvent",
    "CopyActivityLevel",
    "CopyExecutionMetric",
    "CopySignalReview",
    "AutomationConfidence",
    "ChannelProfile",
    "ChannelMessageSample",
    "SignalThread",
    "SignalThreadState",
    "ParsedAction",
    "TradeIntent",
    "TradeIntentState",
    "CopiedTrade",
    "SymbolMapping",
]
