services:
  redis:
    image: redis:7-alpine
    container_name: synctrades-be-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6381:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    volumes:
      - synctrades_redis_data:/data

volumes:
  synctrades_redis_data:
