"""add_is_manual_is_missed_to_trades

Revision ID: 256e11dfea33
Revises: fefa9f3b436c
Create Date: 2026-05-28 16:56:33.513023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '256e11dfea33'
down_revision: Union[str, Sequence[str], None] = 'fefa9f3b436c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('is_manual', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('trades', sa.Column('is_missed', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'is_missed')
    op.drop_column('trades', 'is_manual')
    # ### end Alembic commands ###
