"""add_custom_tags

Revision ID: 2d629be79bc7
Revises: d1e2f3a4b5c6
Create Date: 2026-05-26 00:35:26.804195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d629be79bc7'
down_revision: Union[str, Sequence[str], None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_categories_user_id'), 'tag_categories', ['user_id'], unique=False)
    op.create_table('tag_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['tag_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_options_category_id'), 'tag_options', ['category_id'], unique=False)
    op.create_index(op.f('ix_tag_options_user_id'), 'tag_options', ['user_id'], unique=False)
    op.create_table('trade_tag_selections',
    sa.Column('trade_id', sa.UUID(), nullable=False),
    sa.Column('option_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['tag_options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trade_id', 'option_id')
    )
    op.alter_column('trades', 'sl',
               existing_type=sa.NUMERIC(precision=18, scale=5),
               comment=None,
               existing_comment='Initial stop-loss price level',
               existing_nullable=True)
    op.alter_column('trades', 'tp',
               existing_type=sa.NUMERIC(precision=18, scale=5),
               comment=None,
               existing_comment='Take-profit price level',
               existing_nullable=True)
    op.alter_column('trades', 'magic_number',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='MT5 magic number (0=manual, >0=EA)',
               existing_nullable=True)
    op.alter_column('trades', 'position_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='Broker position ID for grouping partial closes',
               existing_nullable=True)
    op.alter_column('trades', 'trade_source',
               existing_type=postgresql.ENUM('personal', 'copied', name='tradesourceenum'),
               comment=None,
               existing_comment='Trade origin: personal or copied',
               existing_nullable=True)
    op.alter_column('trades', 'mfe',
               existing_type=sa.NUMERIC(precision=18, scale=5),
               comment=None,
               existing_comment='Maximum Favorable Excursion (highest high)',
               existing_nullable=True)
    op.alter_column('trades', 'mae',
               existing_type=sa.NUMERIC(precision=18, scale=5),
               comment=None,
               existing_comment='Maximum Adverse Excursion (lowest low)',
               existing_nullable=True)
    op.drop_index(op.f('ix_trades_account_closed_at_id'), table_name='trades')
    op.alter_column('trading_accounts', 'sync_provider',
               existing_type=postgresql.ENUM('metaapi', 'headless_mt5', name='syncproviderenum'),
               comment=None,
               existing_comment='Sync provider: metaapi (default) or headless_mt5',
               existing_nullable=False,
               existing_server_default=sa.text("'metaapi'::syncproviderenum"))
    op.alter_column('trading_accounts', 'copy_magic_numbers',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               comment=None,
               existing_comment='MT5 magic numbers belonging to copy-trading subscriptions',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trading_accounts', 'copy_magic_numbers',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               comment='MT5 magic numbers belonging to copy-trading subscriptions',
               existing_nullable=True)
    op.alter_column('trading_accounts', 'sync_provider',
               existing_type=postgresql.ENUM('metaapi', 'headless_mt5', name='syncproviderenum'),
               comment='Sync provider: metaapi (default) or headless_mt5',
               existing_nullable=False,
               existing_server_default=sa.text("'metaapi'::syncproviderenum"))
    op.create_index(op.f('ix_trades_account_closed_at_id'), 'trades', ['account_id', 'closed_at', 'id'], unique=False)
    op.alter_column('trades', 'mae',
               existing_type=sa.NUMERIC(precision=18, scale=5),
               comment='Maximum Adverse Excursion (lowest low)',
               existing_nullable=True)
    op.alter_column('trades', 'mfe',
               existing_type=sa.NUMERIC(precision=18, scale=5),
               comment='Maximum Favorable Excursion (highest high)',
               existing_nullable=True)
    op.alter_column('trades', 'trade_source',
               existing_type=postgresql.ENUM('personal', 'copied', name='tradesourceenum'),
               comment='Trade origin: personal or copied',
               existing_nullable=True)
    op.alter_column('trades', 'position_id',
               existing_type=sa.VARCHAR(length=64),
               comment='Broker position ID for grouping partial closes',
               existing_nullable=True)
    op.alter_column('trades', 'magic_number',
               existing_type=sa.INTEGER(),
               comment='MT5 magic number (0=manual, >0=EA)',
               existing_nullable=True)
    op.alter_column('trades', 'tp',
               existing_type=sa.NUMERIC(precision=18, scale=5),
               comment='Take-profit price level',
               existing_nullable=True)
    op.alter_column('trades', 'sl',
               existing_type=sa.NUMERIC(precision=18, scale=5),
               comment='Initial stop-loss price level',
               existing_nullable=True)
    op.drop_table('trade_tag_selections')
    op.drop_index(op.f('ix_tag_options_user_id'), table_name='tag_options')
    op.drop_index(op.f('ix_tag_options_category_id'), table_name='tag_options')
    op.drop_table('tag_options')
    op.drop_index(op.f('ix_tag_categories_user_id'), table_name='tag_categories')
    op.drop_table('tag_categories')
    # ### end Alembic commands ###
