"""add_trading_journal_foundation_tables

Revision ID: 4db0be4616dc
Revises: ef593f8b763f
Create Date: 2026-03-17 12:55:58.402108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4db0be4616dc'
down_revision: Union[str, Sequence[str], None] = 'ef593f8b763f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    DO $$ BEGIN
        CREATE TYPE journaltemplatetypeenum AS ENUM ('daily', 'trade');
    EXCEPTION
        WHEN duplicate_object THEN NULL;
    END $$;
    """)
    op.execute("""
    DO $$ BEGIN
        CREATE TYPE tradingaccounttypeenum AS ENUM ('demo', 'live');
    EXCEPTION
        WHEN duplicate_object THEN NULL;
    END $$;
    """)
    op.execute("""
    DO $$ BEGIN
        CREATE TYPE tradingplatformenum AS ENUM ('MT4', 'MT5');
    EXCEPTION
        WHEN duplicate_object THEN NULL;
    END $$;
    """)
    op.execute("""
    DO $$ BEGIN
        CREATE TYPE tradingaccountstatusenum AS ENUM ('pending_sync', 'synced', 'error', 'disconnected');
    EXCEPTION
        WHEN duplicate_object THEN NULL;
    END $$;
    """)
    op.execute("""
    DO $$ BEGIN
        CREATE TYPE tradedirectionenum AS ENUM ('buy', 'sell');
    EXCEPTION
        WHEN duplicate_object THEN NULL;
    END $$;
    """)
    op.execute("""
    DO $$ BEGIN
        CREATE TYPE tradesessionenum AS ENUM ('asian', 'london', 'new_york', 'london_ny_overlap', 'off_hours');
    EXCEPTION
        WHEN duplicate_object THEN NULL;
    END $$;
    """)
    op.execute("""
    DO $$ BEGIN
        CREATE TYPE journalmessagetypeenum AS ENUM ('text', 'voice', 'image', 'system', 'prompt', 'ai_response');
    EXCEPTION
        WHEN duplicate_object THEN NULL;
    END $$;
    """)

    op.create_table('journal_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('template_type', postgresql.ENUM('daily', 'trade', name='journaltemplatetypeenum', create_type=False), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_templates_owner_id'), 'journal_templates', ['owner_id'], unique=False)
    op.create_table('trading_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('meta_account_id', sa.String(length=64), nullable=False),
    sa.Column('broker_name', sa.String(length=120), nullable=False),
    sa.Column('account_type', postgresql.ENUM('demo', 'live', name='tradingaccounttypeenum', create_type=False), nullable=False),
    sa.Column('platform', postgresql.ENUM('MT4', 'MT5', name='tradingplatformenum', create_type=False), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('status', postgresql.ENUM('pending_sync', 'synced', 'error', 'disconnected', name='tradingaccountstatusenum', create_type=False), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_error_message', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'meta_account_id')
    )
    op.create_index(op.f('ix_trading_accounts_user_id'), 'trading_accounts', ['user_id'], unique=False)
    op.create_table('account_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('equity', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('floating_pnl', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'snapshot_date')
    )
    op.create_index(op.f('ix_account_snapshots_account_id'), 'account_snapshots', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_snapshots_snapshot_date'), 'account_snapshots', ['snapshot_date'], unique=False)
    op.create_table('daily_journals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'trading_date')
    )
    op.create_index(op.f('ix_daily_journals_account_id'), 'daily_journals', ['account_id'], unique=False)
    op.create_index(op.f('ix_daily_journals_trading_date'), 'daily_journals', ['trading_date'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('broker_trade_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', postgresql.ENUM('buy', 'sell', name='tradedirectionenum', create_type=False), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('volume', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('profit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('swap', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('session', postgresql.ENUM('asian', 'london', 'new_york', 'london_ny_overlap', 'off_hours', name='tradesessionenum', create_type=False), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'broker_trade_id')
    )
    op.create_index(op.f('ix_trades_account_id'), 'trades', ['account_id'], unique=False)
    op.create_index(op.f('ix_trades_closed_at'), 'trades', ['closed_at'], unique=False)
    op.create_index(op.f('ix_trades_opened_at'), 'trades', ['opened_at'], unique=False)
    op.create_table('daily_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('win_count', sa.Integer(), nullable=False),
    sa.Column('loss_count', sa.Integer(), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_commission', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross_win', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross_loss', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('best_trade_id', sa.UUID(), nullable=True),
    sa.Column('worst_trade_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['best_trade_id'], ['trades.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['worst_trade_id'], ['trades.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'trading_date')
    )
    op.create_index(op.f('ix_daily_stats_account_id'), 'daily_stats', ['account_id'], unique=False)
    op.create_index(op.f('ix_daily_stats_trading_date'), 'daily_stats', ['trading_date'], unique=False)
    op.create_table('trade_journals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trade_id', sa.UUID(), nullable=False),
    sa.Column('daily_journal_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['daily_journal_id'], ['daily_journals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_journals_daily_journal_id'), 'trade_journals', ['daily_journal_id'], unique=False)
    op.create_index(op.f('ix_trade_journals_trade_id'), 'trade_journals', ['trade_id'], unique=True)
    op.create_table('journal_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('daily_journal_id', sa.UUID(), nullable=True),
    sa.Column('trade_journal_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('message_type', postgresql.ENUM('text', 'voice', 'image', 'system', 'prompt', 'ai_response', name='journalmessagetypeenum', create_type=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('system_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audio_storage_path', sa.String(), nullable=True),
    sa.Column('audio_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('((daily_journal_id IS NOT NULL AND trade_journal_id IS NULL) OR (trade_journal_id IS NOT NULL AND daily_journal_id IS NULL))', name='ck_journal_messages_exactly_one_context'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['daily_journal_id'], ['daily_journals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_journal_id'], ['trade_journals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jm_daily_journal_id', 'journal_messages', ['daily_journal_id'], unique=False)
    op.create_index('ix_jm_trade_journal_id', 'journal_messages', ['trade_journal_id'], unique=False)
    op.create_index(op.f('ix_journal_messages_author_id'), 'journal_messages', ['author_id'], unique=False)
    op.create_index(op.f('ix_journal_messages_created_at'), 'journal_messages', ['created_at'], unique=False)
    op.create_table('journal_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['journal_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_attachments_message_id'), 'journal_attachments', ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_attachments_message_id'), table_name='journal_attachments')
    op.drop_table('journal_attachments')
    op.drop_index(op.f('ix_journal_messages_created_at'), table_name='journal_messages')
    op.drop_index(op.f('ix_journal_messages_author_id'), table_name='journal_messages')
    op.drop_index('ix_jm_trade_journal_id', table_name='journal_messages')
    op.drop_index('ix_jm_daily_journal_id', table_name='journal_messages')
    op.drop_table('journal_messages')
    op.drop_index(op.f('ix_trade_journals_trade_id'), table_name='trade_journals')
    op.drop_index(op.f('ix_trade_journals_daily_journal_id'), table_name='trade_journals')
    op.drop_table('trade_journals')
    op.drop_index(op.f('ix_daily_stats_trading_date'), table_name='daily_stats')
    op.drop_index(op.f('ix_daily_stats_account_id'), table_name='daily_stats')
    op.drop_table('daily_stats')
    op.drop_index(op.f('ix_trades_opened_at'), table_name='trades')
    op.drop_index(op.f('ix_trades_closed_at'), table_name='trades')
    op.drop_index(op.f('ix_trades_account_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_daily_journals_trading_date'), table_name='daily_journals')
    op.drop_index(op.f('ix_daily_journals_account_id'), table_name='daily_journals')
    op.drop_table('daily_journals')
    op.drop_index(op.f('ix_account_snapshots_snapshot_date'), table_name='account_snapshots')
    op.drop_index(op.f('ix_account_snapshots_account_id'), table_name='account_snapshots')
    op.drop_table('account_snapshots')
    op.drop_index(op.f('ix_trading_accounts_user_id'), table_name='trading_accounts')
    op.drop_table('trading_accounts')
    op.drop_index(op.f('ix_journal_templates_owner_id'), table_name='journal_templates')
    op.drop_table('journal_templates')

    op.execute("DROP TYPE IF EXISTS journalmessagetypeenum")
    op.execute("DROP TYPE IF EXISTS tradesessionenum")
    op.execute("DROP TYPE IF EXISTS tradedirectionenum")
    op.execute("DROP TYPE IF EXISTS tradingaccountstatusenum")
    op.execute("DROP TYPE IF EXISTS tradingplatformenum")
    op.execute("DROP TYPE IF EXISTS tradingaccounttypeenum")
    op.execute("DROP TYPE IF EXISTS journaltemplatetypeenum")
    # ### end Alembic commands ###
