"""add_price_images_approval_to_streams

Revision ID: e25205c88f87
Revises: 433280177f3c
Create Date: 2026-03-04 16:24:08.422168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e25205c88f87'
down_revision: Union[str, Sequence[str], None] = '433280177f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streams', sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('streams', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('streams', sa.Column('banner_url', sa.String(), nullable=True))
    op.add_column('streams', sa.Column('require_join_approval', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streams', 'require_join_approval')
    op.drop_column('streams', 'banner_url')
    op.drop_column('streams', 'avatar_url')
    op.drop_column('streams', 'price')
    # ### end Alembic commands ###
