"""add_is_default_to_streams

Revision ID: ef593f8b763f
Revises: d4e9f1a2b3c0
Create Date: 2026-03-11 20:39:07.139340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef593f8b763f'
down_revision: Union[str, Sequence[str], None] = 'd4e9f1a2b3c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streams', sa.Column('is_default', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streams', 'is_default')
    # ### end Alembic commands ###
