"""add_trade_assessment_scores

Revision ID: fefa9f3b436c
Revises: 4da4bd35145f
Create Date: 2026-05-27 19:41:15.310796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fefa9f3b436c'
down_revision: Union[str, Sequence[str], None] = '4da4bd35145f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_journals', sa.Column('execution_quality', sa.Integer(), nullable=True))
    op.add_column('trade_journals', sa.Column('setup_quality', sa.Integer(), nullable=True))
    op.add_column('trade_journals', sa.Column('discipline_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_journals', 'discipline_score')
    op.drop_column('trade_journals', 'setup_quality')
    op.drop_column('trade_journals', 'execution_quality')
    # ### end Alembic commands ###
